# Generated by Django 3.1.7 on 2021-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberoffice',
            name='number_office',
            field=models.IntegerField(),
        ),
    ]
