# Generated by Django 3.1.7 on 2021-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0002_auto_20210313_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberoffice',
            name='number_office',
            field=models.CharField(max_length=30),
        ),
    ]
