# Generated by Django 3.1.7 on 2021-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(),
        ),
    ]
