# Generated by Django 3.1.7 on 2021-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0006_auto_20210318_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(default=None, unique=True),
        ),
    ]
