# Generated by Django 3.1.7 on 2021-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0008_auto_20210318_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(unique=True),
        ),
    ]
