# Generated by Django 3.1.7 on 2021-03-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0009_auto_20210318_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworkings.numberoffice', unique_for_date='datetime_from'),
        ),
    ]
